version: '3'

volumes:
  email_server_local_postgres_data: {}
  email_server_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: email_server_local_django
    container_name: email_server_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: email_server_production_postgres
    container_name: email_server_local_postgres
    volumes:
      - email_server_local_postgres_data:/var/lib/postgresql/data:Z
      - email_server_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: email_server_local_docs
    container_name: email_server_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./email_server:/app/email_server:z
    ports:
      - "9000:9000"
    command: /start-docs
