# Generated by Django 3.2.13 on 2022-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
