# Generated by Django 3.2.13 on 2022-05-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillist',
            options={'verbose_name_plural': 'Mailing List'},
        ),
    ]
